export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const QUANTITY_INCREASE = 'QUANTITY_INCREASE';
export const QUANTITY_DECREASE = 'QUANTITY_DECREASE';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const QUANTITY_INCREASE_WISHLIST = 'QUANTITY_INCREASE_WISHLIST';
export const QUANTITY_DECREASE_WISHLIST = 'QUANTITY_DECREASE_WISHLIST';