export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_FIRST_TIME = 'CHANGE_FIRST_TIME';
export const CHANGE_VARIABLES = 'CHANGE_VARIABLES';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SELLER = 'LOGIN_SELLER';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const SET_CART = 'SET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const QUANTITY_INCREASE = 'QUANTITY_INCREASE';
export const QUANTITY_DECREASE = 'QUANTITY_DECREASE';

export const SET_WISHLIST = 'SET_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';